name: .NET

on:
  release:
    types: [published]

env:
  NUGET_SOURCE_URL: 'https://pkgs.dev.azure.com/servicetitan-packages/nuget/_packaging/servicetitan-nuget/nuget/v3/index.json'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create Package for Nuget.org\
      run: dotnet pack
    - name: Create Package Source
      run: dotnet nuget add source ${{env.NUGET_SOURCE_URL}} --name publishSource --username "user" --password ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text
    - name: Publish Package to Nuget.org
      run: dotnet nuget push ./Xero.NetStandard.OAuth2/bin/Debug/Xero.NetStandard.OAuth2.${{ github.event.release.name }}.nupkg --api-key "az" --source publishSource
